services:
  backend:
    build:
      context: ./backend

    container_name: shortavee-backend

    ports:
      - "8080:8080"

    env_file:
      - ./backend/.env

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend

    container_name: shortavee-frontend

    ports:
      - "5173:5173"

    restart: unless-stopped

    depends_on:
      - backend