apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  DB_HOST: "postgres-postgresql"
  DB_PORT: "5432"
  DB_USER: "shortavee"
  DB_PASSWORD: "Tinyavee123!@#"
  DB_NAME: "shortavee_db"
  JWT_SECRET: "bismillahsettle2026"
