apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  DB_HOST: "postgresql://neondb_owner:npg_GlRfaiOqkI90@ep-soft-bird-at32ocfg-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  DB_PORT: "5432"
  DB_USER: "shortavee"
  DB_PASSWORD: "Tinyavee123!@#"
  DB_NAME: "shortavee_db"
  JWT_SECRET: "bismillahsettle2026"
